### ISSUE TITLE
is this idemsaltenv linux only or also windows

### ISSUE THREAD

**Issue by TheBigBear** [eitrtechnologies/saltenv#6]
Hi, sorry if this is a really silly question. But seeing that idem itself ( and pop ) is cross-platform, I am wondering if this much simpler and leaner looking saltenv as compared to a full windows salt minion is even an option? I would envisage using this to manage windows desktops and laptops ( and maybe even a server or two ) using saltenv over having to install the full salt minion on them.

**Comment by nicholasmhughes** [comment]
This project (saltenv) and the similar idemenv project you referenced are POP applications that manage versions of the Salt and Idem binaries respectively. This means being able to download binaries built with Tiamat and storing them in a location on a system so a user can easily switch between versions and run commands locally.

For Salt, the best use cases for saltenv are local standalone management of a system (like a personal laptop) or testing different released versions. Starting with version 3005, which should be out in the coming weeks, Salt will be releasing its packages where traditional system-Python-installed files will be replaced with Tiamat-built binaries. This means that the Salt application itself will be identical whether you're using saltenv or an installed Salt minion package. The only difference is the higher-level management and use of the application. For large, centrally managed deployments, you'll likely still want to have the full minion installed.

For Idem, it's meant to be a command-line utility to manage cloud infrastructure at this time. So, idemenv is a really good way to manage the installed application versions... just like tfenv for Terraform.

Each underlying binary should work on Windows systems, and if you see any issues running saltenv or idemenv on Windows, please open an issue. Thanks for checking out the projects!
